export const ActionTypes = {
    SET_LIST: "SET_LIST",
    REMOVE_LIST: "REMOVE_LIST",
    SELECTED_GAME: "SELECTED_GAME",
    REMOVE_SELECTED_GAME: "REMOVE_SELECTED_GAME",
    SET_QUERY: "SET_QUERY",
}